apiVersion: v1
kind: ConfigMap
metadata:
  name: redis-configmap
  namespace: dockercoins
data:
  redis-configmap: |
    protected-mode no
    port 6379
    timeout 0
    loglevel notice
    databases 16
    save 900 1
    save 300 10
    save 60 10000
    dbfilename dump.rdb
