apiVersion: v1
kind: Service
metadata:
  name: redis-svc
  namespace: dockercoins
spec:
  type: ClusterIP
  ports:
    - name: redis-svc
      protocol: TCP
      port: 6379
      targetPort: 6379
  selector:
    k8s-app: redis
