apiVersion: v1
kind: Service
metadata:
  name: hasher-svc
  namespace: dockercoins
spec:
  selector:
    k8s-app: hasher
  type: ClusterIP
  ports:
  - name: hasher-svc
    protocol: TCP
    port: 80
    targetPort: 80
