apiVersion: v1
kind: Service
metadata:
  name: webui-svc
  namespace: dockercoins
spec:
  selector:
    k8s-app: webui
  type: ClusterIP
  ports:
  - name: webui-svc
    protocol: TCP
    port: 80
    targetPort: 80

