apiVersion: apps/v1
kind: Deployment
metadata:
  name: worker
  namespace: dockercoins
  labels:
    k8s-app: worker
spec:
  selector:
    matchLabels:
      k8s-app: worker
  template:
    metadata:
      labels:
        k8s-app: worker
    spec:
      containers:
      - name: worker-container
        image: anfurtado/worker:1.0
        ports:
        - containerPort: 6379
      #imagePullSecrets:
      #- name: regcred
