apiVersion: v1
kind: Service
metadata:
  name: rng-svc
  namespace: dockercoins
spec:
  selector:
    k8s-app: rng
  type: NodePort
  ports:
  - name: rng-svc
    protocol: TCP
    port: 80
    targetPort: 80
    nodePort: 32054
